
import { 
  BarChart3, 
  Share2, 
  Key, 
  ShieldCheck, 
  CreditCard, 
  Package, 
  Globe2, 
  Wrench
} from "lucide-react";
import { Category } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "analysis",
    title: "选品分析 Analysis",
    icon: BarChart3,
    items: [
      { id: "a1", name: "德亚销售榜", description: "德国亚马逊销售排行榜", url: "https://www.amazon.de/gp/bestsellers", iconColor: "bg-amber-500", iconInitial: "a" },
      { id: "a2", name: "英亚销售榜", description: "英国亚马逊销售排行榜", url: "https://www.amazon.co.uk/gp/bestsellers", iconColor: "bg-amber-500", iconInitial: "a" },
      { id: "a3", name: "法亚销售榜", description: "法国亚马逊销售排行榜", url: "https://www.amazon.fr/gp/bestsellers", iconColor: "bg-amber-500", iconInitial: "a" },
      { id: "a4", name: "美亚销售榜", description: "美国亚马逊销售排行榜", url: "https://www.amazon.com/gp/bestsellers", iconColor: "bg-amber-500", iconInitial: "a" },
      { id: "a5", name: "美亚新品榜", description: "美国亚马逊新品排行榜", url: "https://www.amazon.com/gp/new-releases", iconColor: "bg-amber-500", iconInitial: "a" },
      { id: "a6", name: "美亚飙升榜", description: "美国亚马逊销售飙升榜", url: "https://www.amazon.com/gp/movers-and-shakers", iconColor: "bg-amber-500", iconInitial: "a" },
      { id: "a7", name: "日亚销售榜", description: "日本亚马逊销售排行榜（需翻墙）", url: "https://www.amazon.co.jp/gp/bestsellers", iconColor: "bg-amber-500", iconInitial: "a" },
      { id: "a8", name: "加大拿销售榜", description: "加拿大亚马逊销售排行榜", url: "https://www.amazon.ca/gp/bestsellers", iconColor: "bg-amber-500", iconInitial: "a+" },
      { id: "a9", name: "Temu Bestsellers", description: "每日更新Temu最受欢迎榜单", url: "https://www.temu.com/bestsellers.html", iconColor: "bg-orange-600", iconInitial: "Tm" },
      { id: "a10", name: "谷歌趋势", description: "查看关键词在Google的搜索次数及变化趋势", url: "https://trends.google.com/", iconColor: "bg-blue-500", iconInitial: "G" },
      { id: "a11", name: "Walmart Bestsellers", description: "沃尔玛平台最受欢迎产品榜单", url: "https://www.walmart.com/cp/best-sellers/1085666", iconColor: "bg-blue-700", iconInitial: "*" },
      { id: "a12", name: "谷歌商机洞察", description: "查看产品类在全球每一个国家的具体市场需求和容量", url: "https://marketfinder.thinkwithgoogle.com/", iconColor: "bg-blue-500", iconInitial: "G" },
      { id: "a13", name: "Most Wished For", description: "亚马逊买家愿望清单", url: "https://www.amazon.com/gp/most-wished-for", iconColor: "bg-gray-900", iconInitial: "a" },
      { id: "a14", name: "Today's Deals", description: "美国亚马逊每日促销", url: "https://www.amazon.com/gp/goldbox", iconColor: "bg-gray-900", iconInitial: "a" },
      { id: "a15", name: "Ebay Daily", description: "Ebay 平台每日促销商品", url: "https://www.ebay.com/globaldeals", iconColor: "bg-green-600", iconInitial: "ebay" },
      { id: "a16", name: "Indiegogo", description: "美国第二大的众筹网站", url: "https://www.indiegogo.com/", iconColor: "bg-pink-600", iconInitial: "GO" },
      { id: "a17", name: "Kickstarter", description: "美国最大的众筹网站", url: "https://www.kickstarter.com/", iconColor: "bg-black", iconInitial: "K" },
    ]
  },
  {
    id: "social",
    title: "社交媒体 Social",
    icon: Share2,
    items: [
      { id: "s1", name: "Facebook", description: "全球最大社交平台", url: "https://facebook.com", iconColor: "bg-blue-600", iconInitial: "f" },
      { id: "s2", name: "YouTube", description: "全球最大的视频网站", url: "https://youtube.com", iconColor: "bg-red-600", iconInitial: "YT" },
      { id: "s3", name: "X (Twitter)", description: "美国微博", url: "https://twitter.com", iconColor: "bg-black", iconInitial: "X" },
      { id: "s4", name: "Instagram", description: "全球最大的图片社交平台", url: "https://instagram.com", iconColor: "bg-gradient-to-tr from-yellow-400 via-red-500 to-purple-500", iconInitial: "In" },
      { id: "s5", name: "Pinterest", description: "瀑布流图片社区 世界最大的图片社交分享网站", url: "https://pinterest.com", iconColor: "bg-red-700", iconInitial: "P" },
      { id: "s6", name: "Reddit", description: "娱乐、社交及新闻网站", url: "https://www.reddit.com/", iconColor: "bg-orange-500", iconInitial: "R" },
      { id: "s7", name: "Quora", description: "美版知乎，全球最大的知识问答社区", url: "https://www.quora.com/", iconColor: "bg-red-800", iconInitial: "Q" },
      { id: "s8", name: "TikTok", description: "海外抖音", url: "https://tiktok.com", iconColor: "bg-black", iconInitial: "♪" },
      { id: "s9", name: "WhatsApp", description: "Facebook旗下的全球性移动聊天工具", url: "https://whatsapp.com", iconColor: "bg-green-500", iconInitial: "W" },
      { id: "s10", name: "LinkedIn", description: "全球知名的职场社交平台-领英", url: "https://linkedin.com", iconColor: "bg-blue-700", iconInitial: "in" },
      { id: "s11", name: "Telegram", description: "俗称“电报”，是一款全球知名度非常高的加密聊天工具", url: "https://telegram.org/", iconColor: "bg-cyan-500", iconInitial: "T" },
      { id: "s12", name: "Discord", description: "基于兴趣的综合性社交媒体平台", url: "https://discord.com/", iconColor: "bg-indigo-600", iconInitial: "D" },
    ]
  },
  {
    id: "keywords",
    title: "关键词 Keywords",
    icon: Key,
    items: [
      { id: "k1", name: "卖家精灵", description: "查竞品出单词/流量词，关键词精准反查/购买量", url: "https://www.sellersprite.com/", iconColor: "bg-orange-100 text-orange-600", iconInitial: "S" },
      { id: "k2", name: "Sif关键词体系", description: "查广告架构、运营打法、流量结构、体系化运营关键词", url: "https://www.sif.com/", iconColor: "bg-emerald-100 text-emerald-600", iconInitial: "Sif" },
      { id: "k3", name: "领星关键词管理", description: "关键词实时监控/出单与词频分析/关键词快照、抢占首", url: "https://www.lingxing.com/", iconColor: "bg-blue-100 text-blue-600", iconInitial: "L" },
      { id: "k4", name: "精准关键词排名", description: "精度飞跃24倍，每小时更新 关键词排名，垄断流量精", url: "https://www.junglescout.cn/", iconColor: "bg-orange-100 text-orange-500", iconInitial: "JS" },
      { id: "k5", name: "KeywordToolDominator", description: "亚马逊卖家类目调研/选品/关键词分析神器", url: "https://www.keywordtooldominator.com/", iconColor: "bg-slate-50 text-orange-500 border border-slate-200", iconInitial: "K" },
      { id: "k6", name: "MerchantWords", description: "拥有海量亚马逊关键词数据，关键词挖掘必备", url: "https://www.merchantwords.com/", iconColor: "bg-orange-100 text-orange-400", iconInitial: "M" },
      { id: "k7", name: "Wordtracker", description: "关键词跟踪工具", url: "https://www.wordtracker.com/", iconColor: "bg-blue-500 text-white", iconInitial: "W" },
    ]
  },
  {
    id: "patents",
    title: "商标专利 Patent",
    icon: ShieldCheck,
    items: [
      { id: "p1", name: "欧洲商标局", description: "负责管理欧盟商标和注册的共同体外观设计", url: "https://euipo.europa.eu/", iconColor: "bg-white border border-cyan-200 text-cyan-600", iconInitial: "EU" },
      { id: "p2", name: "英国商标局", description: "负责知识产权的官方政府机构", url: "https://www.gov.uk/government/organisations/intellectual-property-office", iconColor: "bg-black text-white", iconInitial: "UK" },
      { id: "p3", name: "美国商标局", description: "美国商标局官网", url: "https://www.uspto.gov/", iconColor: "bg-white border border-slate-200 text-slate-800", iconInitial: "R" },
      { id: "p4", name: "WIPO商标查询", description: "WIPO商标查询系统", url: "https://www3.wipo.int/branddb/en/", iconColor: "bg-slate-600 text-white", iconInitial: "W" },
      { id: "p5", name: "中国商标局", description: "中国商标局", url: "http://sbj.cnipa.gov.cn/", iconColor: "bg-white border border-red-200 text-red-600", iconInitial: "CN" },
      { id: "p6", name: "Trademarkia", description: "商标保护方面是世界上最值得信赖的品牌", url: "https://www.trademarkia.com/", iconColor: "bg-orange-100 text-orange-500", iconInitial: "T" },
      { id: "p7", name: "欧洲专利局", description: "专利申请的检索和审查以及欧洲专利的授予", url: "https://www.epo.org/", iconColor: "bg-white border border-red-200 text-red-600", iconInitial: "EP" },
      { id: "p8", name: "英国专利局", description: "英国专利局", url: "https://www.gov.uk/topic/intellectual-property/patents", iconColor: "bg-black text-white", iconInitial: "UK" },
      { id: "p9", name: "美国专利局", description: "美国专利局", url: "https://www.uspto.gov/patents", iconColor: "bg-white border border-slate-200 text-blue-800", iconInitial: "US" },
      { id: "p10", name: "WIPO专利查询", description: "WIPO专利查询", url: "https://patentscope.wipo.int/", iconColor: "bg-slate-500 text-white", iconInitial: "W" },
      { id: "p11", name: "中国专利检索", description: "中国专利检索", url: "http://cpquery.cnipa.gov.cn/", iconColor: "bg-white border border-red-200 text-red-600", iconInitial: "CN" },
      { id: "p12", name: "innojoy", description: "简单好用的专利搜索引擎", url: "https://www.innojoy.com/", iconColor: "bg-red-600 text-white", iconInitial: "i" },
    ]
  },
  {
    id: "payment",
    title: "收款支付 Payment",
    icon: CreditCard,
    items: [
      { id: "pay1", name: "PayPal", description: "全球性的在线支付公司", url: "https://www.paypal.com/", iconColor: "bg-white border border-blue-200 text-blue-700", iconInitial: "P" },
      { id: "pay2", name: "HUBFX", description: "英国欧盟27和美国的本地银行收款账号", url: "https://www.hubfx.co/", iconColor: "bg-white border border-slate-200 text-slate-800", iconInitial: "H" },
      { id: "pay3", name: "Masterpass", description: "Masterpass 是一种电子钱包服务", url: "https://www.mastercard.us/en-us/personal/ways-to-pay/click-to-pay.html", iconColor: "bg-white border border-red-200 text-red-500", iconInitial: "●" },
      { id: "pay4", name: "Visa pay", description: "Visa Pay是一款便捷、安全的非接触式支付平台", url: "https://www.visa.com/", iconColor: "bg-white border border-blue-200 text-blue-800", iconInitial: "V" },
      { id: "pay5", name: "腾讯智汇鹅", description: "跨境卖家和企业出海支付优选品牌", url: "https://global.tenpay.com/", iconColor: "bg-black text-yellow-400", iconInitial: "鹅" },
      { id: "pay6", name: "万里汇 (WorldFirst)", description: "蚂蚁集团旗下品牌，多平台多币种极速到账", url: "https://www.worldfirst.com/", iconColor: "bg-red-600 text-white", iconInitial: "万" },
      { id: "pay7", name: "Pingpong", description: "多平台多币种极速到账；支持11国VAT、出口退税", url: "https://www.pingpongx.com/", iconColor: "bg-blue-600 text-white", iconInitial: "P" },
      { id: "pay8", name: "空中云汇", description: "亚马逊收款首选，收款0费率，卡支付返现高达1.6%", url: "https://www.airwallex.com/", iconColor: "bg-white border border-orange-200 text-orange-500", iconInitial: "A" },
      { id: "pay9", name: "网易支付", description: "网易官方出品，亚马逊收款首选，0汇损新风新得", url: "https://epay.163.com/", iconColor: "bg-blue-600 text-white", iconInitial: "网" },
      { id: "pay10", name: "连连支付", description: "全牌照，无汇损，费率0.7%封顶，5分钟内到账", url: "https://www.lianlianpay.com/", iconColor: "bg-blue-500 text-white", iconInitial: "L" },
      { id: "pay11", name: "Payoneer", description: "本地账号免汇损，多币种转换，灵活银行提现", url: "https://www.payoneer.com/", iconColor: "bg-white border border-orange-200 text-orange-500", iconInitial: "O" },
      { id: "pay12", name: "iPayLinks艾贝盈", description: "新客注册享好礼，多平台福利大放送，多快好", url: "https://www.ipaylinks.com/", iconColor: "bg-white border border-slate-200 text-slate-400", iconInitial: "i" },
    ]
  },
  {
    id: "sourcing",
    title: "货源网站 Sourcing",
    icon: Package,
    items: [
      { id: "src1", name: "1688", description: "全球领先的采购批发平台", url: "https://www.1688.com/", iconColor: "bg-orange-500", iconInitial: "1688" },
      { id: "src2", name: "淘宝", description: "深受欢迎的网购零售平台", url: "https://www.taobao.com/", iconColor: "bg-orange-600", iconInitial: "淘" },
      { id: "src3", name: "阿里国际", description: "全球专业的国际外贸出口、海外B2B跨境贸易平台", url: "https://www.alibaba.com/", iconColor: "bg-orange-400", iconInitial: "Al" },
      { id: "src4", name: "拼多多", description: "国内主流电商平台", url: "https://www.pinduoduo.com/", iconColor: "bg-red-600", iconInitial: "拼" },
      { id: "src5", name: "中国制造网", description: "专注中国制造的B2B电子商务平台", url: "https://www.made-in-china.com/", iconColor: "bg-pink-50 text-red-600", iconInitial: "M" },
      { id: "src6", name: "义乌购", description: "义乌小商品批发市场官方网站", url: "https://www.yiwugo.com/", iconColor: "bg-orange-500", iconInitial: "义" },
      { id: "src7", name: "网商园", description: "网商园是全国最早专业的服装服饰类货源分销平台", url: "https://www.wsy.com/", iconColor: "bg-blue-500", iconInitial: "网" },
      { id: "src8", name: "赛盈", description: "主打欧美中大件海外仓精品一件代发分销服务", url: "https://www.saleyee.cn/", iconColor: "bg-white border border-slate-200 text-slate-800", iconInitial: "赛" },
      { id: "src9", name: "美适分销", description: "致力于为跨境卖家解决货源问题，降低跨境起步门槛", url: "https://www.meishifenxiao.com/", iconColor: "bg-yellow-400 text-black", iconInitial: "MS" },
      { id: "src10", name: "大健云仓", description: "为全球家居供应商及零售商提供线上/线下的综合交易及", url: "https://www.gigab2b.com/", iconColor: "bg-white border border-blue-200 text-blue-600", iconInitial: "大" },
      { id: "src11", name: "飞飞鱼定制", description: "全球性的S2B2C柔性供应链服务平台", url: "https://www.sdsdiy.com/", iconColor: "bg-blue-700 text-white", iconInitial: "飞" },
      { id: "src12", name: "慧聪网", description: "中国B端企业服务商和行业门户", url: "https://www.hc360.com/", iconColor: "bg-white border border-orange-200 text-orange-600", iconInitial: "慧" },
      { id: "src13", name: "青创网", description: "B2B鞋服供应链数智平台，青创网汇聚全国鞋服产业带", url: "https://www.17qcc.com/", iconColor: "bg-white border border-green-200 text-green-500", iconInitial: "Q" },
      { id: "src14", name: "DOBA", description: "国外分销平台", url: "https://www.doba.com/", iconColor: "bg-green-600", iconInitial: "D" },
      { id: "src15", name: "Oberlo", description: "国外一件代发平台", url: "https://www.oberlo.com/", iconColor: "bg-blue-600 text-white", iconInitial: "Ob" },
      { id: "src16", name: "拖尼斯", description: "国内做分销的网站", url: "http://www.tuonisi.com/", iconColor: "bg-pink-500 text-white", iconInitial: "拖" },
      { id: "src17", name: "搜款网", description: "全国著名服装批发平台", url: "https://www.vvic.com/", iconColor: "bg-pink-500 text-white", iconInitial: "搜" },
      { id: "src18", name: "17货源", description: "专业服装批发网站，广州服装批发一手货源平台", url: "https://www.17zwd.com/", iconColor: "bg-red-600 text-white", iconInitial: "17" },
      { id: "src19", name: "指纹科技", description: "跨境热销品类齐全，无限SKU，1件起订", url: "https://www.hicustom.com/", iconColor: "bg-white border border-slate-200 text-blue-500", iconInitial: "Hi" },
      { id: "src20", name: "CJdropshipping", description: "官方合作分销服务商", url: "https://cjdropshipping.com/", iconColor: "bg-orange-500 text-white", iconInitial: "CJ" },
    ]
  },
  {
    id: "uk",
    title: "英国网站 UK",
    icon: Globe2,
    items: [
      { id: "uk1", name: "eBay", description: "英国线上拍卖及购物网站", url: "https://www.ebay.co.uk/", iconColor: "bg-white border border-slate-200 text-blue-600", iconInitial: "ebay" },
      { id: "uk2", name: "Argos", description: "英国家喻户晓的百货零售连锁商", url: "https://www.argos.co.uk/", iconColor: "bg-red-600 text-white", iconInitial: "Arg" },
      { id: "uk3", name: "SHEIN", description: "英国时尚服装市场网站", url: "https://www.shein.co.uk/", iconColor: "bg-black text-white", iconInitial: "S" },
      { id: "uk4", name: "Tesco", description: "英国最大的零售公司，也是世界三大零售商之一", url: "https://www.tesco.com/", iconColor: "bg-white border border-blue-200 text-blue-600", iconInitial: "Tesco" },
      { id: "uk5", name: "B&Q", description: "跨国的大型DIY用家庭与园艺工具材料连锁店与大卖场", url: "https://www.diy.com/", iconColor: "bg-orange-500 text-white", iconInitial: "B&Q" },
      { id: "uk6", name: "Wayfair", description: "主要销售英国的家具和家居用品", url: "https://www.wayfair.co.uk/", iconColor: "bg-purple-600 text-white", iconInitial: "W" },
      { id: "uk7", name: "Dunelm", description: "英国最大的家居产品零售商", url: "https://www.dunelm.com/", iconColor: "bg-white border border-green-200 text-green-600", iconInitial: "Dunelm" },
      { id: "uk8", name: "Wilko", description: "英国有名的high-street连锁超市", url: "https://www.wilko.com/", iconColor: "bg-red-700 text-white", iconInitial: "wilko" },
      { id: "uk9", name: "TheRange", description: "一家英国多渠道品牌零售商", url: "https://www.therange.co.uk/", iconColor: "bg-white border border-orange-200 text-orange-500", iconInitial: "Range" },
      { id: "uk10", name: "Screwfix", description: "英国最大的贸易工具、配件和硬件产品的多渠道零售商", url: "https://www.screwfix.com/", iconColor: "bg-blue-600 text-white", iconInitial: "SF" },
      { id: "uk11", name: "Wickes", description: "英国DIY和家居装饰领域的丰富品牌", url: "https://www.wickes.co.uk/", iconColor: "bg-blue-900 text-white", iconInitial: "Wickes" },
      { id: "uk12", name: "Homebase", description: "英国家居装修零售商", url: "https://www.homebase.co.uk/", iconColor: "bg-white border border-green-200 text-green-600", iconInitial: "Home" },
      { id: "uk13", name: "Toolstation", description: "英国发展最快的工具、配件和建筑用品供应商之一", url: "https://www.toolstation.com/", iconColor: "bg-white border border-blue-200 text-blue-600", iconInitial: "TS" },
      { id: "uk14", name: "Bmstores", description: "英国家居折扣零售商", url: "https://www.bmstores.co.uk/", iconColor: "bg-white border border-orange-200 text-orange-600", iconInitial: "bm" },
      { id: "uk15", name: "TKmaxx", description: "英国的折扣零售商场", url: "https://www.tkmaxx.com/", iconColor: "bg-red-600 text-white", iconInitial: "TK" },
      { id: "uk16", name: "Currys", description: "英国电子产品零售连锁商店", url: "https://www.currys.co.uk/", iconColor: "bg-purple-800 text-white", iconInitial: "currys" },
      { id: "uk17", name: "ManoMano", description: "DIY、家居装修和园艺产品的在线平台", url: "https://www.manomano.co.uk/", iconColor: "bg-teal-500 text-white", iconInitial: "M" },
      { id: "uk18", name: "Halfords", description: "英国一家汽车零件、汽车改装、野营和旅游设备", url: "https://www.halfords.com/", iconColor: "bg-orange-500 text-white", iconInitial: "halfords" },
      { id: "uk19", name: "Very", description: "英国的服饰在线零售商城", url: "https://www.very.co.uk/", iconColor: "bg-pink-600 text-white", iconInitial: "very" },
      { id: "uk20", name: "OnBuy", description: "英国新兴电商平台", url: "https://www.onbuy.com/gb/", iconColor: "bg-white border border-blue-200 text-blue-500", iconInitial: "OnBuy" },
      { id: "uk21", name: "HotUKDeals", description: "英国最大促销导购网站", url: "https://www.hotukdeals.com/", iconColor: "bg-black text-white", iconInitial: "hot" },
      { id: "uk22", name: "PicClick", description: "英国比价网站", url: "https://picclick.co.uk/", iconColor: "bg-white border border-blue-200 text-blue-500", iconInitial: "Pic" },
      { id: "uk23", name: "Gumtree", description: "英国最大的分类信息网站", url: "https://www.gumtree.com/", iconColor: "bg-green-700 text-white", iconInitial: "G" },
      { id: "uk24", name: "Shpock", description: "在线交易平台,主要用于个人用户之间买卖闲置物品", url: "https://www.shpock.com/en-gb", iconColor: "bg-white border border-green-200 text-green-500", iconInitial: "S" },
      { id: "uk25", name: "Preloved", description: "英国二手物品交易网站", url: "https://www.preloved.co.uk/", iconColor: "bg-white border border-orange-200 text-orange-500", iconInitial: "❤" },
      { id: "uk26", name: "BackMarket", description: "英国二手交易平台", url: "https://www.backmarket.co.uk/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "<<" },
      { id: "uk27", name: "Zalando", description: "欧洲领先的在线时尚公司", url: "https://www.zalando.co.uk/", iconColor: "bg-orange-500 text-white", iconInitial: "Z" },
      { id: "uk28", name: "Vinted", description: "欧洲二手电商交易平台", url: "https://www.vinted.co.uk/", iconColor: "bg-teal-500 text-white", iconInitial: "V" },
    ]
  },
  {
    id: "germany",
    title: "德国网站 Germany",
    icon: Globe2,
    items: [
      { id: "de1", name: "eBay", description: "德国线上拍卖及购物网站", url: "https://www.ebay.de/", iconColor: "bg-white border border-blue-200 text-blue-600", iconInitial: "ebay" },
      { id: "de2", name: "Otto.de", description: "德国第二大电商平台,次于亚马逊", url: "https://www.otto.de/", iconColor: "bg-white border border-red-200 text-red-600", iconInitial: "OTTO" },
      { id: "de3", name: "Zalando", description: "德国最大时尚电子商务公司", url: "https://www.zalando.de/", iconColor: "bg-orange-500", iconInitial: "Z" },
      { id: "de4", name: "Kaufland", description: "欧洲第5大食品零售商", url: "https://www.kaufland.de/", iconColor: "bg-red-600", iconInitial: "K" },
      { id: "de5", name: "Wayfair", description: "主要销售德国的家具和家居用品", url: "https://www.wayfair.de/", iconColor: "bg-purple-600", iconInitial: "W" },
      { id: "de6", name: "ManoMano", description: "DIY、家居装修和园艺产品的在线平台", url: "https://www.manomano.de/", iconColor: "bg-emerald-500", iconInitial: "M" },
      { id: "de7", name: "速卖通", description: "速卖通德国站是速卖通在欧洲的重要站点之一", url: "https://de.aliexpress.com/", iconColor: "bg-orange-600", iconInitial: "速" },
      { id: "de8", name: "MediaMarkt", description: "德国和欧洲第一大电子零售商", url: "https://www.mediamarkt.de/", iconColor: "bg-red-700", iconInitial: "MM" },
      { id: "de9", name: "iDealo", description: "德国最大的比价网站", url: "https://www.idealo.de/", iconColor: "bg-blue-800", iconInitial: "id" },
      { id: "de10", name: "Mydealz", description: "德国最大促销导购网站", url: "https://www.mydealz.de/", iconColor: "bg-blue-600", iconInitial: "my" },
      { id: "de11", name: "PicClick", description: "德国比价网站", url: "https://picclick.de/", iconColor: "bg-white border border-blue-200 text-blue-500", iconInitial: "Pic" },
      { id: "de12", name: "eBay-Kleinanzeigen", description: "德国在线分类信息门户网站", url: "https://www.kleinanzeigen.de/", iconColor: "bg-white border border-green-200 text-green-700", iconInitial: "eb" },
      { id: "de13", name: "Lidl.de", description: "德国连锁超市的在线购物平台", url: "https://www.lidl.de/", iconColor: "bg-blue-700", iconInitial: "Lidl" },
      { id: "de14", name: "AldiSued", description: "世界知名的德国零售企业", url: "https://www.aldi-sued.de/", iconColor: "bg-blue-900", iconInitial: "A" },
      { id: "de15", name: "Vinted", description: "Vinted德国站，为当地消费者提供二手商品服务", url: "https://www.vinted.de/", iconColor: "bg-teal-500", iconInitial: "V" },
      { id: "de16", name: "BackMarket", description: "德国二手交易平台", url: "https://www.backmarket.de/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "<<" },
      { id: "de17", name: "Home24", description: "德国家具和家居饰品电商平台", url: "https://www.home24.de/", iconColor: "bg-white border border-orange-200 text-orange-500", iconInitial: "home" },
      { id: "de18", name: "Tchibo", description: "德语区烘焙咖啡市场的龙头品牌，拥有多样化的生活用品", url: "https://www.tchibo.de/", iconColor: "bg-blue-900", iconInitial: "Tc" },
      { id: "de19", name: "Baur", description: "德国时装、家具和生活摆设的电商平台", url: "https://www.baur.de/", iconColor: "bg-white border border-orange-200 text-orange-500", iconInitial: "b." },
      { id: "de20", name: "DM", description: "主要销售日用品、母婴产品、化妆品保健品和健康食品", url: "https://www.dm.de/", iconColor: "bg-white border border-slate-200 text-slate-800", iconInitial: "dm" },
      { id: "de21", name: "OBI", description: "德国建材装饰零售市场", url: "https://www.obi.de/", iconColor: "bg-orange-500", iconInitial: "OBI" },
      { id: "de22", name: "Markt", description: "德国主营花园家具、生活家居的电商平台", url: "https://www.markt.de/", iconColor: "bg-white border border-orange-200 text-orange-500", iconInitial: "m" },
    ]
  },
  {
    id: "france",
    title: "法国网站 France",
    icon: Globe2,
    items: [
      { id: "fr1", name: "eBay", description: "eBay在法国开设的分站", url: "https://www.ebay.fr/", iconColor: "bg-white border border-blue-200 text-blue-600", iconInitial: "ebay" },
      { id: "fr2", name: "Cdiscount", description: "法国第二大的电子商务平台", url: "https://www.cdiscount.com/", iconColor: "bg-white border border-red-200 text-red-600", iconInitial: "C" },
      { id: "fr3", name: "Fnac", description: "知名的文化产品和电器产品零售商", url: "https://www.fnac.com/", iconColor: "bg-yellow-500", iconInitial: "Fnac" },
      { id: "fr4", name: "ManoMano", description: "欧洲最大的DIY、家具和园艺商店", url: "https://www.manomano.fr/", iconColor: "bg-emerald-500", iconInitial: "M" },
      { id: "fr5", name: "Zalando", description: "提供服装、鞋类、配饰和美容产品", url: "https://www.zalando.fr/", iconColor: "bg-orange-500", iconInitial: "Z" },
      { id: "fr6", name: "法国乐天", description: "乐天旗下欧洲最大的电商平台", url: "https://fr.shopping.rakuten.com/", iconColor: "bg-red-600 text-white", iconInitial: "R" },
      { id: "fr7", name: "Darty", description: "法国知名家电零售商，为全法第一大家电零售商KFSA集团雄", url: "https://www.darty.com/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "DARTY" },
      { id: "fr8", name: "速卖通", description: "法国站主要销售时尚服装、家居、数码、玩具、配件", url: "https://fr.aliexpress.com/", iconColor: "bg-orange-600", iconInitial: "速" },
      { id: "fr9", name: "Vinted", description: "Vinted法国站是法国最受欢迎的二手交易平台", url: "https://www.vinted.fr/", iconColor: "bg-teal-500", iconInitial: "V" },
      { id: "fr10", name: "BackMarket", description: "法国二手交易平台", url: "https://www.backmarket.fr/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "<<" },
      { id: "fr11", name: "Dealabs", description: "法国最大促销导购网站", url: "https://www.dealabs.com/", iconColor: "bg-black text-white", iconInitial: "D" },
      { id: "fr12", name: "PicClick", description: "法国比价网站", url: "https://picclick.fr/", iconColor: "bg-white border border-blue-200 text-blue-500", iconInitial: "Pic" },
      { id: "fr13", name: "Lidl.fr", description: "主要销售食品、日常用品和其他商品", url: "https://www.lidl.fr/", iconColor: "bg-blue-700", iconInitial: "Lidl" },
      { id: "fr14", name: "La Redoute", description: "法国时尚服饰电商平台", url: "https://www.laredoute.fr/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "La" },
      { id: "fr15", name: "Auchan", description: "法国第二大大型综合超市集团", url: "https://www.auchan.fr/", iconColor: "bg-red-600 text-white", iconInitial: "Au" },
      { id: "fr16", name: "LeBoncoin", description: "法国本土知名的生活分类广告网站，类似中国的58", url: "https://www.leboncoin.fr/", iconColor: "bg-orange-500 text-white", iconInitial: "LB" },
      { id: "fr17", name: "iDealo", description: "法国比价网站", url: "https://www.idealo.fr/", iconColor: "bg-blue-900 text-white", iconInitial: "i" },
      { id: "fr18", name: "Castorama", description: "法国DIY和家庭装修工具及用品的连锁零售商", url: "https://www.castorama.fr/", iconColor: "bg-blue-600 text-white", iconInitial: "C" },
      { id: "fr19", name: "Conforama", description: "法国知名的家具销售平台，也是欧洲第二大家居用品商", url: "https://www.conforama.fr/", iconColor: "bg-white border border-red-200 text-red-600", iconInitial: "C" },
      { id: "fr20", name: "法国家乐福", description: "世界最大的零售商之一", url: "https://www.carrefour.fr/", iconColor: "bg-blue-600 text-white", iconInitial: "C" },
      { id: "fr21", name: "LeroyMerlin", description: "欧洲排名第1的大型国际家装建材零售集团", url: "https://www.leroymerlin.fr/", iconColor: "bg-green-500 text-white", iconInitial: "LM" },
      { id: "fr22", name: "Rue du Commerce", description: "法国知名高科技电商平台", url: "https://www.rueducommerce.fr/", iconColor: "bg-black text-white", iconInitial: "Rue" },
    ]
  },
  {
    id: "italy",
    title: "意大利网站 Italy",
    icon: Globe2,
    items: [
      { id: "it1", name: "eBay", description: "eBay在意大利开设的分站", url: "https://www.ebay.it/", iconColor: "bg-white border border-slate-200 text-blue-600", iconInitial: "ebay" },
      { id: "it2", name: "Zalando", description: "销售世界品牌服装，包括儿童服装，还有品牌包 鞋", url: "https://www.zalando.it/", iconColor: "bg-orange-500", iconInitial: "Z" },
      { id: "it3", name: "ManoMano", description: "欧洲最大的DIY、家具和园艺商店", url: "https://www.manomano.it/", iconColor: "bg-emerald-500", iconInitial: "M" },
      { id: "it4", name: "速卖通", description: "阿里巴巴旗下唯一面向意大利市场打造的在线交易平台", url: "https://it.aliexpress.com/", iconColor: "bg-orange-600", iconInitial: "速" },
      { id: "it5", name: "MediaWorld", description: "专门从事消费电子产品零售的德国跨国连锁店", url: "https://www.mediaworld.it/", iconColor: "bg-red-600", iconInitial: "MW" },
      { id: "it6", name: "ePrice", description: "一家在线百货商店", url: "https://www.eprice.it/", iconColor: "bg-yellow-400 text-black", iconInitial: "eP" },
      { id: "it7", name: "Subito", description: "提供最简单，最快，最安全的在线买卖服务", url: "https://www.subito.it/", iconColor: "bg-red-500", iconInitial: "S" },
      { id: "it8", name: "iDealo", description: "欧洲最出色的价格比较器之一", url: "https://www.idealo.it/", iconColor: "bg-blue-900", iconInitial: "i" },
      { id: "it9", name: "PicClick", description: "意大利比价网站", url: "https://picclick.it/", iconColor: "bg-white border border-blue-200 text-blue-500", iconInitial: "Pic" },
      { id: "it10", name: "Unieuro", description: "一家专门从事消费电子和家用电器的意大利零售连锁店", url: "https://www.unieuro.it/", iconColor: "bg-blue-900 text-orange-400", iconInitial: "U" },
      { id: "it11", name: "BackMarket", description: "意大利二手交易平台", url: "https://www.backmarket.it/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "<<" },
      { id: "it12", name: "Lidl.it", description: "提供广泛的商品种类，包括食品 日用品 家居用品", url: "https://www.lidl.it/", iconColor: "bg-blue-700", iconInitial: "Lidl" },
      { id: "it13", name: "Vinted", description: "欧洲领先的在线二手购物平台之一，主要面向时尚领域", url: "https://www.vinted.it/", iconColor: "bg-teal-500", iconInitial: "V" },
      { id: "it14", name: "LeroyMerlin", description: "为意大利用户提供了一站式的家居建材购物平台", url: "https://www.leroymerlin.it/", iconColor: "bg-green-500", iconInitial: "LM" },
    ]
  },
  {
    id: "spain",
    title: "西班牙网站 Spain",
    icon: Globe2,
    items: [
      { id: "es1", name: "速卖通", description: "为消费者提供了一系列高性价比的产品", url: "https://es.aliexpress.com/", iconColor: "bg-orange-600", iconInitial: "速" },
      { id: "es2", name: "eBay", description: "eBay在西班牙开设的分站", url: "https://www.ebay.es/", iconColor: "bg-white border border-blue-200 text-blue-600", iconInitial: "ebay" },
      { id: "es3", name: "Miravia", description: "欧洲西班牙品质时尚综合型电商平台", url: "https://www.miravia.es/", iconColor: "bg-purple-600", iconInitial: "M" },
      { id: "es4", name: "Zalando", description: "涵盖了时尚、生活、体育等领域的电子商务平台", url: "https://www.zalando.es/", iconColor: "bg-orange-500", iconInitial: "Z" },
      { id: "es5", name: "ManoMano", description: "欧洲最大的DIY、家具和园艺商店", url: "https://www.manomano.es/", iconColor: "bg-emerald-500", iconInitial: "M" },
      { id: "es6", name: "MediaMarkt", description: "专门从事消费电子产品零售的跨国连锁店", url: "https://www.mediamarkt.es/", iconColor: "bg-red-600", iconInitial: "MM" },
      { id: "es7", name: "El Corte Inglés", description: "欧洲著名的百货公司", url: "https://www.elcorteingles.es/", iconColor: "bg-green-700", iconInitial: "E" },
      { id: "es8", name: "Carrefour", description: "家乐福西班牙站可以在线购买食品饮料 电子电器", url: "https://www.carrefour.es/", iconColor: "bg-blue-600", iconInitial: "C" },
      { id: "es9", name: "Fnac", description: "知名的文化产品和电器产品零售商", url: "https://www.fnac.es/", iconColor: "bg-yellow-500", iconInitial: "Fnac" },
      { id: "es10", name: "BackMarket", description: "西班牙二手交易平台", url: "https://www.backmarket.es/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "<<" },
      { id: "es11", name: "Worten", description: "著名的专业售卖电子产品的电商平台", url: "https://www.worten.es/", iconColor: "bg-red-600", iconInitial: "worten" },
      { id: "es12", name: "iDealo", description: "欧洲最出色的价格比较器之一", url: "https://www.idealo.es/", iconColor: "bg-blue-900", iconInitial: "i" },
      { id: "es13", name: "Lidl.es", description: "Lidl西班牙站提供了广泛的商品种类，包括食品 饮料", url: "https://www.lidl.es/", iconColor: "bg-blue-700", iconInitial: "Lidl" },
      { id: "es14", name: "Leroy Merlin", description: "为西班牙消费者提供了一站式的家居购物体验", url: "https://www.leroymerlin.es/", iconColor: "bg-green-500", iconInitial: "LM" },
      { id: "es15", name: "Vinted", description: "Vinted西班牙站是西班牙最受欢迎的二手平台", url: "https://www.vinted.es/", iconColor: "bg-teal-500", iconInitial: "V" },
    ]
  },
  {
    id: "portugal",
    title: "葡萄牙网站 Portugal",
    icon: Globe2,
    items: [
      { id: "pt1", name: "速卖通", description: "速卖通葡萄牙站，提供了服饰、家居用品、电子产品", url: "https://pt.aliexpress.com/", iconColor: "bg-orange-600", iconInitial: "速" },
      { id: "pt2", name: "KuantoKusta", description: "一家消费电子产品，家具，化妆品，美食，家居装饰", url: "https://www.kuantokusta.pt/", iconColor: "bg-orange-500", iconInitial: "K" },
      { id: "pt3", name: "PCDIGA", description: "为私人和企业客户提供个性化和专业的服务", url: "https://www.pcdiga.com/", iconColor: "bg-black text-white", iconInitial: "PC" },
      { id: "pt4", name: "Leroy Merlin", description: "葡萄牙市场上家居装修和建筑用品的领导者之一", url: "https://www.leroymerlin.pt/", iconColor: "bg-green-500 text-white", iconInitial: "LM" },
      { id: "pt5", name: "Worten", description: "著名的专业售卖电子产品的电商平台", url: "https://www.worten.pt/", iconColor: "bg-red-600 text-white", iconInitial: "worten" },
      { id: "pt6", name: "Continente", description: "您的网上购物大卖场", url: "https://www.continente.pt/", iconColor: "bg-red-600 text-white", iconInitial: "C" },
      { id: "pt7", name: "MediaMarkt", description: "欧洲第一大电子零售商", url: "https://mediamarkt.pt/", iconColor: "bg-red-600 text-white", iconInitial: "MM" },
      { id: "pt8", name: "Lidl.pt", description: "葡萄牙最具影响力的零售商之一", url: "https://www.lidl.pt/", iconColor: "bg-blue-700 text-white", iconInitial: "Lidl" },
      { id: "pt9", name: "Fnac", description: "知名的文化产品和电器产品零售商", url: "https://www.fnac.pt/", iconColor: "bg-yellow-500 text-white", iconInitial: "fnac" },
      { id: "pt10", name: "El Corte Inglés", description: "欧洲著名的百货公司", url: "https://www.elcorteingles.pt/", iconColor: "bg-green-700 text-white", iconInitial: "E" },
      { id: "pt11", name: "OLX.pt", description: "全球性二手商品分类信息平台", url: "https://www.olx.pt/", iconColor: "bg-teal-500 text-white", iconInitial: "olx" },
      { id: "pt12", name: "Vinted", description: "Vinted葡萄牙站，提供了服饰 鞋子 手袋 配饰", url: "https://www.vinted.pt/", iconColor: "bg-teal-500 text-white", iconInitial: "V" },
      { id: "pt13", name: "Auchan", description: "葡萄牙大型综合超市集团", url: "https://www.auchan.pt/", iconColor: "bg-red-600 text-white", iconInitial: "Au" },
      { id: "pt14", name: "BackMarket", description: "葡萄牙二手交易平台", url: "https://www.backmarket.pt/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "<<" },
    ]
  },
  {
    id: "russia",
    title: "俄罗斯网站 Russia",
    icon: Globe2,
    items: [
      { id: "ru1", name: "Wildberries", description: "俄罗斯本土最大的线上平台之一", url: "https://www.wildberries.ru/", iconColor: "bg-purple-700 text-white", iconInitial: "wb" },
      { id: "ru2", name: "DNSShop", description: "电子产品零售商", url: "https://www.dns-shop.ru/", iconColor: "bg-orange-500 text-white", iconInitial: "DNS" },
      { id: "ru3", name: "M.Video", description: "主营家用电器和电子产品的俄罗斯在线商店", url: "https://www.mvideo.ru/", iconColor: "bg-red-600 text-white", iconInitial: "M" },
      { id: "ru4", name: "Avito", description: "俄罗斯最大的分类信息网站, 涵盖的类别从商品", url: "https://www.avito.ru/", iconColor: "bg-blue-500 text-white", iconInitial: "Avito" },
      { id: "ru5", name: "Ozon", description: "俄罗斯第二大电商平台", url: "https://www.ozon.ru/", iconColor: "bg-blue-600 text-white", iconInitial: "ozon" },
      { id: "ru6", name: "Joom", description: "俄罗斯移动电商平台", url: "https://www.joom.com/ru", iconColor: "bg-black text-white", iconInitial: "J" },
      { id: "ru7", name: "Citilink", description: "俄罗斯专注于3C家电领域以及汽车配件的电商平台", url: "https://www.citilink.ru/", iconColor: "bg-orange-500 text-white", iconInitial: "C" },
      { id: "ru8", name: "Mail.ru", description: "俄罗斯最主流的电子邮件提供商", url: "https://mail.ru/", iconColor: "bg-blue-600 text-white", iconInitial: "@" },
      { id: "ru9", name: "YandexMarket", description: "俄罗斯Yandex旗下的综合购物网站", url: "https://market.yandex.ru/", iconColor: "bg-red-600 text-white", iconInitial: "Y" },
      { id: "ru10", name: "Yandex Translate", description: "Yandex公司为您提供的企业开发的高质量的机器翻译", url: "https://translate.yandex.ru/", iconColor: "bg-red-600 text-white", iconInitial: "文" },
      { id: "ru11", name: "Eldorado", description: "俄罗斯第二大生活用品电子零售商", url: "https://www.eldorado.ru/", iconColor: "bg-green-600 text-white", iconInitial: "E" },
      { id: "ru12", name: "速卖通", description: "中国最大的跨境出口B2C平台", url: "https://aliexpress.ru/", iconColor: "bg-orange-600 text-white", iconInitial: "速" },
      { id: "ru13", name: "Mega Market", description: "一家主营家用电器产品的俄罗斯电商平台", url: "https://megamarket.ru/", iconColor: "bg-purple-600 text-white", iconInitial: "M" },
      { id: "ru14", name: "Mst在线商店", description: "主营电子配件以及手机配件等产品", url: "https://shop.mts.ru/", iconColor: "bg-red-600 text-white", iconInitial: "M" },
    ]
  },
  {
    id: "turkey",
    title: "土耳其网站 Turkey",
    icon: Globe2,
    items: [
      { id: "tr1", name: "Trendyol", description: "土耳其最大的电商平台", url: "https://www.trendyol.com/", iconColor: "bg-orange-500 text-white", iconInitial: "trendyol" },
      { id: "tr2", name: "Mediamarkt", description: "欧洲第一大电子产品零售商", url: "https://www.mediamarkt.com.tr/", iconColor: "bg-red-600 text-white", iconInitial: "MM" },
      { id: "tr3", name: "速卖通", description: "针对土耳其地区的用户，提供了本地化的服务，包括语", url: "https://tr.aliexpress.com/", iconColor: "bg-red-600 text-white", iconInitial: "速" },
      { id: "tr4", name: "Hepsiburada", description: "土耳其领先的电子商务网站", url: "https://www.hepsiburada.com/", iconColor: "bg-orange-600 text-white", iconInitial: "H" },
      { id: "tr5", name: "Koctas", description: "土耳其最著名的家居装饰零售商", url: "https://www.koctas.com.tr/", iconColor: "bg-orange-500 text-white", iconInitial: "Koctas" },
      { id: "tr6", name: "Teknosa", description: "土耳其最大的电子产品电商平台之一", url: "https://www.teknosa.com/", iconColor: "bg-orange-500 text-white", iconInitial: "T" },
      { id: "tr7", name: "Gittigidiyor", description: "土耳其的一家拍卖型网站", url: "https://www.gittigidiyor.com/", iconColor: "bg-blue-500 text-white", iconInitial: "G" },
      { id: "tr8", name: "Akakce", description: "购物比价网站", url: "https://www.akakce.com/", iconColor: "bg-blue-500 text-white", iconInitial: "A" },
      { id: "tr9", name: "N11", description: "土耳其新兴电商平台", url: "https://www.n11.com/", iconColor: "bg-red-600 text-white", iconInitial: "n11" },
      { id: "tr10", name: "PttAVM", description: "土耳其最可靠的国家电子商务平台", url: "https://www.pttavm.com/", iconColor: "bg-yellow-400 text-black", iconInitial: "P" },
    ]
  },
  {
    id: "netherlands",
    title: "荷兰网站 Netherlands",
    icon: Globe2,
    items: [
      { id: "nl1", name: "BOL", description: "荷兰和比利时买家首选的购物网站", url: "https://www.bol.com/nl/", iconColor: "bg-blue-800 text-white", iconInitial: "bol" },
      { id: "nl2", name: "Zalando", description: "主营服饰的在线时尚零售商", url: "https://www.zalando.nl/", iconColor: "bg-orange-500 text-white", iconInitial: "Z" },
      { id: "nl3", name: "速卖通", description: "速卖通荷兰站的全球市场渗透率排名第一", url: "https://nl.aliexpress.com/", iconColor: "bg-orange-600 text-white", iconInitial: "速" },
      { id: "nl4", name: "Coolblue", description: "电子产品及家庭用品百货商店", url: "https://www.coolblue.nl/", iconColor: "bg-blue-500 text-white", iconInitial: "cool" },
      { id: "nl5", name: "Mediamarkt", description: "荷兰电器和数码商品店", url: "https://www.mediamarkt.nl/", iconColor: "bg-red-600 text-white", iconInitial: "MM" },
      { id: "nl6", name: "Kruidvat", description: "荷兰连锁的药品和生活用品超市", url: "https://www.kruidvat.nl/", iconColor: "bg-red-600 text-white", iconInitial: "K" },
      { id: "nl7", name: "Wehkamp", description: "荷兰领先的电商网站", url: "https://www.wehkamp.nl/", iconColor: "bg-red-500 text-white", iconInitial: "W" },
      { id: "nl8", name: "HEMA", description: "荷兰全品类连锁零售商", url: "https://www.hema.nl/", iconColor: "bg-red-600 text-white", iconInitial: "HEMA" },
      { id: "nl9", name: "debijenkorf", description: "荷兰最著名的高级百货连锁店", url: "https://www.debijenkorf.nl/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "db" },
      { id: "nl10", name: "Etos", description: "荷兰最大的连锁药店之一", url: "https://www.etos.nl/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "Etos" },
      { id: "nl11", name: "LeenBakker", description: "主营家具和室内设计的连锁店", url: "https://www.leenbakker.nl/", iconColor: "bg-pink-600 text-white", iconInitial: "LB" },
      { id: "nl12", name: "OTTO", description: "世界上最大电子电子商务公司之一", url: "https://www.otto.nl/", iconColor: "bg-red-600 text-white", iconInitial: "OTTO" },
      { id: "nl13", name: "Vidaxl", description: "一家国际在线零售商", url: "https://www.vidaxl.nl/", iconColor: "bg-purple-700 text-white", iconInitial: "vida" },
      { id: "nl14", name: "Kieskeurig", description: "一个比价购物网站", url: "https://www.kieskeurig.nl/", iconColor: "bg-red-700 text-white", iconInitial: "K" },
      { id: "nl15", name: "Beslist", description: "荷兰在线购物平台", url: "https://www.beslist.nl/", iconColor: "bg-blue-500 text-white", iconInitial: "beslist" },
      { id: "nl16", name: "Vergelijk", description: "荷兰当地比较知名的电商比价平台", url: "https://www.vergelijk.nl/", iconColor: "bg-yellow-400 text-black", iconInitial: "V" },
      { id: "nl17", name: "Marktplaats", description: "荷兰二手交易平台", url: "https://www.marktplaats.nl/", iconColor: "bg-orange-400 text-white", iconInitial: "M" },
      { id: "nl18", name: "BackMarket", description: "荷兰二手交易平台", url: "https://www.backmarket.nl/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "<<" },
      { id: "nl19", name: "Vinted", description: "用户可以在平台上买卖二手服装 配饰和其他物品", url: "https://www.vinted.nl/", iconColor: "bg-teal-500 text-white", iconInitial: "V" },
      { id: "nl20", name: "Lidl.nl", description: "为当地居民提供便利的购物选择，销售各种商品", url: "https://www.lidl.nl/", iconColor: "bg-blue-700 text-white", iconInitial: "Lidl" },
    ]
  },
  {
    id: "czech",
    title: "捷克网站 Czech",
    icon: Globe2,
    items: [
      { id: "cz1", name: "Hornbach", description: "德国广受关注的建材市场", url: "https://www.hornbach.cz/", iconColor: "bg-orange-500 text-white", iconInitial: "H" },
      { id: "cz2", name: "Favi", description: "捷克地区最大的家具和家装电商平台", url: "https://favi.cz/", iconColor: "bg-red-800 text-white", iconInitial: "FAVI" },
      { id: "cz3", name: "Baumax", description: "连锁超市Baumax在捷克开设的分站", url: "https://www.baumax.cz/", iconColor: "bg-yellow-500 text-white", iconInitial: "b" },
      { id: "cz4", name: "4Home", description: "4home在捷克开设的分站", url: "https://www.4home.cz/", iconColor: "bg-teal-500 text-white", iconInitial: "4Home" },
      { id: "cz5", name: "Lidl.cz", description: "Lidl捷克站是捷克10个最佳购物平台之一", url: "https://www.lidl.cz/", iconColor: "bg-blue-600 text-white", iconInitial: "Lidl" },
      { id: "cz6", name: "JYSK", description: "欧洲的一家零售外资公司", url: "https://jysk.cz/", iconColor: "bg-blue-900 text-white", iconInitial: "JYSK" },
      { id: "cz7", name: "Megaknihy", description: "Megaknihy在捷克开设的分站", url: "https://www.megaknihy.cz/", iconColor: "bg-red-600 text-white", iconInitial: "M" },
      { id: "cz8", name: "Mall", description: "捷克第二大互联网零售商", url: "https://www.mall.cz/", iconColor: "bg-red-600 text-white", iconInitial: "M" },
      { id: "cz9", name: "Xxxlutz", description: "欧洲名列前茅的专业家具卖场", url: "https://www.xxxlutz.cz/", iconColor: "bg-red-600 text-white", iconInitial: "X" },
      { id: "cz10", name: "Datart", description: "专注于消费电子产品的领先零售商", url: "https://www.datart.cz/", iconColor: "bg-blue-900 text-yellow-400", iconInitial: "Datart" },
      { id: "cz11", name: "Zbozi", description: "Zbozi.cz 会为您找到最低的价格", url: "https://www.zbozi.cz/", iconColor: "bg-red-600 text-white", iconInitial: "Z" },
      { id: "cz12", name: "Heureka", description: "非营利性非营利组织，由科学中心基金会运营", url: "https://www.heureka.cz/", iconColor: "bg-green-500 text-black", iconInitial: "H" },
      { id: "cz13", name: "Bazos", description: "分类信息，广告，集市，面向所有人的广告", url: "https://www.bazos.cz/", iconColor: "bg-orange-500 text-white", iconInitial: "@" },
      { id: "cz14", name: "Onlineshop", description: "家具电器平台Onlineshop", url: "https://www.onlineshop.cz/", iconColor: "bg-green-600 text-white", iconInitial: "O" },
      { id: "cz15", name: "Alza", description: "随时随地快速便捷购物，为公司和个体经营者提供优", url: "https://www.alza.cz/", iconColor: "bg-green-500 text-white", iconInitial: "a" },
      { id: "cz16", name: "Kaufland", description: "欧洲最大零售商Schwarz集团旗下电商平台", url: "https://www.kaufland.cz/", iconColor: "bg-red-600 text-white", iconInitial: "K" },
      { id: "cz17", name: "Allegro", description: "波兰最受欢迎的电商平台Allegro在捷克开设的新站", url: "https://allegro.cz/", iconColor: "bg-orange-500 text-white", iconInitial: "allegro" },
      { id: "cz18", name: "CZC", description: "最大的在线计算机和电子产品商店之一", url: "https://www.czc.cz/", iconColor: "bg-white border border-slate-200 text-red-600", iconInitial: "CZC" },
      { id: "cz19", name: "Okay", description: "最大的电气和家具零售商", url: "https://www.okay.cz/", iconColor: "bg-white border border-yellow-400 text-yellow-500", iconInitial: "Okay" },
      { id: "cz20", name: "Zalando", description: "主营时尚产品的电子商务平台，提供货到付款服务", url: "https://www.zalando.cz/", iconColor: "bg-orange-500 text-white", iconInitial: "Z" },
      { id: "cz21", name: "Vinted", description: "捷克电商市场的重要参与者，拥有超过200万的活", url: "https://www.vinted.cz/", iconColor: "bg-teal-500 text-white", iconInitial: "V" },
    ]
  },
  {
    id: "slovakia",
    title: "斯洛伐克站 Slovakia",
    icon: Globe2,
    items: [
      { id: "sk1", name: "Mall", description: "销售家用电器，电子产品，笔记本电脑，电脑，户外等", url: "https://www.mall.sk/", iconColor: "bg-red-600 text-white", iconInitial: "M" },
      { id: "sk2", name: "Favi", description: "家具和装饰销售平台，汇集了450+电子商店和实体店", url: "https://favi.sk/", iconColor: "bg-red-800 text-white", iconInitial: "FAVI" },
      { id: "sk3", name: "Datart", description: "专注于销售电子产品的领先零售商", url: "https://www.datart.sk/", iconColor: "bg-blue-900 text-yellow-400", iconInitial: "Datart" },
      { id: "sk4", name: "Alza", description: "随时随地快速便捷购物，为公司和个体经营者提供优惠", url: "https://www.alza.sk/", iconColor: "bg-white border border-green-500 text-green-600", iconInitial: "a" },
      { id: "sk5", name: "Heureka", description: "非营利性组织，由科学中心基金会运营", url: "https://www.heureka.sk/", iconColor: "bg-green-500 text-black", iconInitial: "H" },
      { id: "sk6", name: "Bazos", description: "分类信息，广告，集市，面向所有人的广告", url: "https://www.bazos.sk/", iconColor: "bg-orange-500 text-white", iconInitial: "@" },
      { id: "sk7", name: "Lidl", description: "折扣连锁店，最高质量的日常用品，价格最便宜", url: "https://www.lidl.sk/", iconColor: "bg-blue-600 text-white", iconInitial: "Lidl" },
      { id: "sk8", name: "BackMarket", description: "斯洛伐克二手交易平台", url: "https://www.backmarket.sk/", iconColor: "bg-white border border-slate-200 text-black", iconInitial: "<<" },
      { id: "sk9", name: "Kaufland", description: "欧洲最大零售商Schwarz集团旗下电商平台", url: "https://www.kaufland.sk/", iconColor: "bg-red-600 text-white", iconInitial: "K" },
      { id: "sk10", name: "Zalando", description: "主营品类从世界知名品牌到本地品牌应有尽有", url: "https://www.zalando.sk/", iconColor: "bg-orange-500 text-white", iconInitial: "Z" },
      { id: "sk11", name: "Vinted", description: "Vinted斯洛伐克站，是斯洛伐克最大的二手电商网站之", url: "https://www.vinted.sk/", iconColor: "bg-teal-500 text-white", iconInitial: "V" },
    ]
  },
  {
    id: "tools",
    title: "常用工具 Tools",
    icon: Wrench,
    items: [
      { id: "t1", name: "DeepL", description: "全球最准确的翻译工具", url: "https://www.deepl.com/", iconColor: "bg-blue-900", iconInitial: "D" },
      { id: "t2", name: "XE Currency", description: "实时汇率查询", url: "https://www.xe.com/", iconColor: "bg-blue-600", iconInitial: "X" },
      { id: "t3", name: "17Track", description: "全球物流查询平台", url: "https://www.17track.net/", iconColor: "bg-orange-500", iconInitial: "17" },
      { id: "t4", name: "Time.is", description: "世界时间查询", url: "https://time.is/", iconColor: "bg-black", iconInitial: "T" },
    ]
  }
];
